### ISSUE TITLE
哥们 最近我也在研究这个ip2region库，有些问题讨论下

### ISSUE THREAD

**Issue by LastKing** [yourtion/node-ip2region#10]
这个ip2region 库的这些转化是怎么进行的？
数据怎么挂钩的，只知道ip转化乘以不同的数字转化成一个相对有意义的数字，然后在数据库中进行挂钩，还有库中很多的偏移都是什么意思。。。一脸懵逼。。
这涉及到哪些基础知识，还望指点。
敬请赐教！~！~谢谢！~，在此打扰了。

**Comment by yourtion** [comment]
数据格式参考原作者的文章： http://dongyado.com/tool/2016/08/18/structure-of-ip2region-database-file/

IP到数字转换可以参考：http://www.cnblogs.com/livingintruth/archive/2012/12/29/2839187.html

偏移就是根据一开始的数据结构决定，包括搜索算法在作者的文章也有详细的说明

**Comment by LastKing** [comment]
谢谢指导！~！~3Q
