### ISSUE TITLE
ip data is not enough, such as 223.104.5.175 for shanghai ,could you update much more? thank you.

### ISSUE THREAD

**Issue by cliffwang2018** [yourtion/node-ip2region#22]
or is there any to update the db by myself, Thank you .

**Comment by yourtion** [comment]
the data is base on https://github.com/lionsoul2014/ip2region#6-%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90ip2regiondb%E6%96%87%E4%BB%B6 

you can add by your self.

and use you owm db `new IP2Region({ dbPath: '/tmp/db.db' });`

**Comment by yourtion** [comment]
fixed
