### ISSUE TITLE
207.148.91. || 45.250.239. 等网段查询的都不是正确的结果

### ISSUE THREAD

**Issue by wudiansi** [yourtion/node-ip2region#27]
如题
207.148.91. 的网段应该是日本的 但是返回了加拿大
45.250.239. 的应该是柬埔寨的 返回了加拿大。

**Comment by yourtion** [comment]
我验证了一下，数据是正确的，请问你用的是什么版本？

![image](https://user-images.githubusercontent.com/1475301/64488051-76580f80-d275-11e9-8d69-66833fb6a47c.png)

**Comment by wudiansi** [comment]
找到原因了 是我这边的问题  很好用的库工具  感谢分享
